# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip
COPY Mes_app/app.py /app
RUN pip install fastapi uvicorn PyPDF2 python-multipart

EXPOSE 5000

CMD ["uvicorn", "Mes_app.app:app", "--host", "0.0.0.0", "--port", "5000"]