services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=your-secret-key
    volumes:
      - db_data:/app
    networks:
      - mes-network

  token-api:
    build:
      context: ./token_api
      dockerfile: Dockerfile.token
    container_name: token-api
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET_KEY=your-secret-key
    volumes:
      - token_db_data:/app
    networks:
      - mes-network

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile.mcp
    container_name: mcp
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=sop-pdfs
      - API_URL=http://api:5000
      - API_USERNAME=admin
      - API_PASSWORD=password123
    depends_on:
      api:
        condition: service_started
      token-api:
        condition: service_started
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
      minio:
        condition: service_started
    command: >
      sh -c "pip install mcpo && mcpo --port 8000 -- python src/main.py"
    restart: unless-stopped
    networks:
      - mes-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mes-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - mes-network
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      mcp:
        condition: service_started
      ollama:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mes-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - mes-network

networks:
  mes-network:
    driver: bridge

volumes:
  db_data:
  token_db_data:
  qdrant_data:
  openwebui_data:
  ollama_data:
  minio_data: