version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./:/app


  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile.mcp
    container_name: mcp
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - api
      - open-webui
    command: >
      sh -c "pip install mcpo && mcpo --port 8000 -- mcp run src/main.py"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - openwebui_data:/app/backend/data
    depends_on:
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"



volumes:
  qdrant_data:
  openwebui_data:
  ollama_data:
